#!/usr/bin/env node

require('rubico/global')
const cronist = require('cronist')
const fs = require('fs')
const FileSystem = require('./internal/FileSystem')
const walkPathForJSFilePaths = require('./internal/walkPathForJSFilePaths')
const exampleArguments1Map = require('./internal/exampleArguments1Map.js')
const { inspect } = require('util')

const readFileUtf8 = path => fs.promises.readFile(path, { encoding: 'utf8' })

const createMdastFile = async function (source, dest, options = {}) {
  await pipe(source, [
    readFileUtf8,
    cronist.parseMarkdown,
    data => fs.promises.writeFile(dest, `
export default ${inspect(data, {
  depth: Infinity,
  maxArrayLength: null,
  maxStringLength: Infinity,
})}
  `.trim()),
  ])
}

const createCronistFile = async function (source, dest, options = {}) {
  const { requiredKeys, ignoreDirs, Arche } = options

  const creator = { createElement() {} }
  const CreatorElement = Arche(creator)

  await pipe(source, [
    curry.arity(2, walkPathForJSFilePaths, __, { ignoreDirs }),

    flatMap(async fileName => pipe(fileName, [
      readFileUtf8,
      cronist,

      filter(data => data.name && data.docs && Object.keys(data.mdast).length > 1),

      // map(omit(['docs'])),

      flatMap(function* (data) {
        if (data.name == 'DocumentElement.{ELEMENT_NAME}') {
          for (const methodName in CreatorElement) {
            if (methodName == 'creator') {
              continue
            }
            const methodData = pipe(data, [
              JSON.stringify,
              text => {
                const exampleArguments =
                  exampleArguments1Map.get(`DocumentElement.${methodName}`) ?? ''
                return text
                  .replace(/{ELEMENT_NAME}/g, methodName)
                  .replace(/{LOWER_ELEMENT_NAME}/g, methodName.toLowerCase())
                  .replace(/{EXAMPLE_ARGUMENTS_1}/g, exampleArguments)
              },
              JSON.parse,
            ])
            yield methodData
          }
        } else if (data.name == 'ReactElement.{ELEMENT_NAME}') {
          for (const methodName in CreatorElement) {
            if (methodName == 'creator') {
              continue
            }
            const methodData = pipe(data, [
              JSON.stringify,
              text => {
                const exampleArguments =
                  exampleArguments1Map.get(`ReactElement.${methodName}`) ?? ''
                return text
                  .replace(/{ELEMENT_NAME}/g, methodName)
                  .replace(/{LOWER_ELEMENT_NAME}/g, methodName.toLowerCase())
                  .replace(/{EXAMPLE_ARGUMENTS_1}/g, exampleArguments)
              },
              JSON.parse,
            ])
            yield methodData
          }
        } else {
          yield data
        }
      }),

      map(assign({ fileName })),
    ])),

    data => {
      data.find(item => item.name == 'Arche').methods = []

      data.find(item => item.name == 'DocumentElement').methods =
        transform(data, compose([
          Transducer.filter(item => item.name.startsWith('DocumentElement.')),
          Transducer.map(item => pipe(item, [
            JSON.stringify,
            text => text.replace(/DocumentElement\./g, ''),
            JSON.parse,
          ])),
        ]), [])

      data.find(item => item.name == 'ReactElement').methods =
        transform(data, compose([
          Transducer.filter(item => item.name.startsWith('ReactElement.')),
          Transducer.map(item => pipe(item, [
            JSON.stringify,
            text => text.replace(/ReactElement\./g, ''),
            JSON.parse,
          ])),
        ]), [])

      return data
    },

    filter(item => (
      !item.name.startsWith('DocumentElement.')
      && !item.name.startsWith('ReactElement.')
    )),

    data => fs.promises.writeFile(dest, `
export default ${inspect(data, {
  depth: Infinity,
  maxArrayLength: null,
  maxStringLength: Infinity,
})}
  `.trim()),
  ])
}

// createMdast() -> Promise<>
const createMdast = async function () {
  const Arche = require('../Arche')
  const ArcheVersion = require('../Arche/package').version
  const ArcheMajorVersion = ArcheVersion.split('.')[0]

  console.log(`Creating mdast/Arche-v${ArcheMajorVersion}-readme.js`)
  await createMdastFile(
    `${__dirname}/../Arche/README.md`,
    `${__dirname}/public/mdast/Arche-v${ArcheMajorVersion}-readme.js`,
  )

  console.log(`Creating cronist/Arche-v${ArcheMajorVersion}.js`)
  await createCronistFile(
    `${__dirname}/../Arche`,
    `${__dirname}/public/cronist/Arche-v${ArcheMajorVersion}.js`,
    {
      requiredKeys: ['name', 'docs'],
      ignoreDirs: ['node_modules', 'archive'],
      Arche,
    },
  )
}

if (require.main == module) {
  createMdast()
}

module.exports = createMdast
